(let ((ql-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (when (probe-file ql-init) (load ql-init)))
(ql:quickload :fiveam)
(asdf:load-asd (truename "githack.asd"))
(ql:quickload :githack)
(ql:quickload "githack/kademlia")
(ql:quickload "githack/kademlia-test")
(unless (uiop:symbol-call "GITHACK-KADEMLIA-TEST" "RUN-KADEMLIA-TESTS")
  (error "kademlia tests failed"))
