;;; -*- Mode: Lisp; coding: utf-8; -*-

(defpackage "GITHACK-TEST"
  (:use "COMMON-LISP" "FIVEAM")
  (:import-from "GITHACK"
                "GIT-OBJECT"
                "SHA"
                "GET-REPOSITORY"
                "GET-LOADED?"
                "GIT-BLOB"
                "GET-PAYLOAD"
                "SERIALIZE-ATOM"
                "DESERIALIZE-ATOM"
                "GIT-TREE"
                "GET-ENTRIES"
                "INFER-GIT-MODE"
                "SERIALIZE-TREE"
                "DESERIALIZE-TREE"
                "GIT-COMMIT"
                "GET-TREE"
                "GET-PARENTS"
                "GET-AUTHOR"
                "GET-COMMITTER"
                "GET-TIMESTAMP"
                "GET-MESSAGE"
                "SERIALIZE-COMMIT"
                "DESERIALIZE-COMMIT"
                "GIT-TYPE"
                "INFLATE-GIT-PROXY"
                "GIT-BRANCH"
                "GET-NAME"
                "GET-TARGET"
                "GIT-SHOW-REF-SHA"
                "GIT-UPDATE-REF"
                "RESOLVE-BRANCH"
                "UPDATE-BRANCH"
                "GIT-REPOSITORY"
                "GET-PATHNAME"
                "*REPOSITORY*"
                "GET-BRANCH"
                "GET-MODE"
                "CALL-WITH-REPOSITORY"
                "GIT-TRANSACTION"
                "GET-GIT-REPOSITORY"
                "GET-TARGET-BRANCH"
                "GET-STATUS"
                "GET-RESULT"
                "GIT-HASH-OBJECT"
                "CALL-WITH-GIT-TRANSACTION"
                "COMMIT-GIT-TRANSACTION"
                "ABORT-GIT-TRANSACTION"
                "PERSISTENT-CONS"
                "PERSISTENT-CAR"
                "PERSISTENT-CDR"
                "PERSISTENT-CONS-LENGTH"
                "PERSISTENT-CONS-PROPER"
                "SERIALIZE-PERSISTENT-CONS"
                "DESERIALIZE-PERSISTENT-CONS"
                "+PERSISTENT-CONS-README+"
                "GIT-CAT-FILE"
                "%ENSURE-BLOB-LOADED"
                "WRAP-ATOMIC-COMMIT-ROOT"
                "RESOLVE-COMMIT-ROOT"
                "+ATOMIC-WRAPPER-README+"
                "WITH-GIT-TRANSACTION"
                "CALL-WITH-TRANSACTION"
                "WITH-TRANSACTION"
                "PERSISTENT-VECTOR"
                "PERSISTENT-VECTOR-LENGTH"
                "PERSISTENT-VECTOR-ELEMENT-TYPE"
                "SERIALIZE-PERSISTENT-VECTOR"
                "DESERIALIZE-PERSISTENT-VECTOR"
                "PERSISTENT-VECTOR-REF"
                "%ENSURE-PERSISTENT-VECTOR-LOADED"
                "+PERSISTENT-VECTOR-README+"
                "PERSISTENT-ARRAY"
                "PERSISTENT-ARRAY-DIMENSIONS"
                "PERSISTENT-ARRAY-ELEMENT-TYPE"
                "SERIALIZE-PERSISTENT-ARRAY"
                "DESERIALIZE-PERSISTENT-ARRAY"
                "PERSISTENT-ARRAY-REF"
                "+PERSISTENT-ARRAY-README+"
                "%PERSISTENT-ARRAY-DATA"
                "PERSISTENT-STANDARD-CLASS"
                "PERSISTENT-DIRECT-SLOT-DEFINITION"
                "PERSISTENT-EFFECTIVE-SLOT-DEFINITION"
                "PERSISTENT-SLOT-DEFINITION-TRANSIENT"
                "PERSISTENT-OBJECT"
                "PERSISTENT-OBJECT-VERSION"
                "SERIALIZE-PERSISTENT-OBJECT"
                "DESERIALIZE-PERSISTENT-OBJECT"
                "%PERSISTENT-OBJECT-INITIALIZER-PAYLOAD"
                "PERSISTENT-STRUCT"
                "DEFINE-PERSISTENT-STRUCT"
                "PERSISTENT-HASH-TABLE"
                "PERSISTENT-HASH-TABLE-P"
                "PERSISTENT-HASH-TABLE-TEST"
                "PERSISTENT-HASH-TABLE-COUNT"
                "PERSISTENT-HASH-TABLE-BUCKETS"
                "PHASH-MAKE"
                "PHASH-GET"
                "PHASH-PUT"
                "PHASH-REMOVE")
  (:export "GITHACK-SUITE"
           "RUN-GITHACK-TESTS"))

(in-package "GITHACK-TEST")

(def-suite githack-suite
  :description "Top-level suite for all GitHack tests.")

(defun run-githack-tests ()
  "Run every GitHack test and explain the results to
*STANDARD-OUTPUT*. Returns true iff every test passed."
  (run! 'githack-suite))
